SELECT
loc.NUMERO_RESERVA,
cli.NOME,
loc.DATA_INICIO,
loc.DATA_FIM,
loc.CPF,
loc.ID_CARRO,
car.MODELO,
loc.ID_FUNCIONARIO,
func.NOME
FROM LOCACOES loc
INNER JOIN CLIENTES cli
ON loc.CPF = cli.CPF
INNER JOIN CARROS car
ON loc.ID_CARRO = car.ID_CARRO
INNER JOIN FUNCIONARIOS func
ON loc.ID_FUNCIONARIO = func.ID_FUNCIONARIO
ORDER BY loc.NUMERO_RESERVA