SELECT
loc.NUMERO_RESERVA,
cli.NOME_CLIENTE,
loc.DATA_INICIO,
loc.DATA_FIM,
loc.CPF,
loc.ID_VEICULO,
car.MODELO,
loc.ID_FUNCIONARIO,
func.NOME
FROM LOCACOES loc
INNER JOIN CLIENTES cli
ON loc.CPF = cli.CPF
INNER JOIN CARROS car
ON loc.ID_VEICULO = car.ID_VEICULO
INNER JOIN FUNCIONARIOS func
ON loc.ID_FUNCIONARIO = func.ID_FUNCIONARIO
ORDER BY loc.NUMERO_RESERVA