erDiagram
    CLIENTE {
        CHAR CPF PK
        VARCHAR NOME_CLIENTE
        CHAR CNH
    }

    FUNCIONARIO {
        INT ID_FUNCIONARIO PK
        VARCHAR NOME
        VARCHAR CARGO
    }

    CARRO {
        INT ID_CARRO PK
        VARCHAR MODELO
        VARCHAR PLACA
        VARCHAR CATEGORIA
        DECIMAL VALOR_DIARIA
    }

    LOCACAO {
        INT NUMERO_RESERVA PK
        DATE DATA_INICIO
        DATE DATA_FIM
        CHAR CPF FK
        INT ID_VEICULO FK
        INT ID_FUNCIONARIO FK
    }

    CLIENTE ||--o{ LOCACAO : "realiza"
    FUNCIONARIO ||--o{ LOCACAO : "atua "
    CARRO ||--o{ LOCACAO : " é usado"
