/*Apaga os relacionamentos*/
ALTER TABLE LABDATABASE.LOCACOES DROP CONSTRAINT CLIENTES_LOCACOES_FK;
ALTER TABLE LABDATABASE.LOCACOES DROP CONSTRAINT CARROS_LOCACOES_FK;
ALTER TABLE LABDATABASE.LOCACOES DROP CONSTRAINT FUNCIONARIOS_LOCACOES_FK;

/*Apaga as tabelas*/
DROP TABLE LABDATABASE.CLIENTES;
DROP TABLE LABDATABASE.CARROS;
DROP TABLE LABDATABASE.FUNCIONARIOS;
DROP TABLE LABDATABASE.LOCACOES;

/*Apaga as sequences*/
DROP SEQUENCE LABDATABASE.CARROS_ID_CARRO_SEQ;
DROP SEQUENCE LABDATABASE.FUNCIONARIOS_ID_FUNCIONARIO_SEQ;
DROP SEQUENCE LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ;

/*Cria as tabelas*/
CREATE TABLE LABDATABASE.CLIENTES (
		CPF VARCHAR2(11) NOT NULL, 
		NOME VARCHAR2(250) NOT NULL, 
		CNH VARCHAR2 (11) NOT NULL, 
		CONSTRAINT CLIENTES_PK PRIMARY KEY (CPF)
);

CREATE TABLE LABDATABASE.CARROS (
		ID_CARRO NUMBER NOT NULL,
		PLACA VARCHAR2(7) NOT NULL,
		CATEGORIA VARCHAR2 (15) NOT NULL, 
		VALOR_DIARIA NUMBER NOT NULL, 
		CONSTRAINT CARROS_PK PRIMARY KEY (ID_CARRO)
);

CREATE TABLE LABDATABASE.FUNCIONARIOS (
		ID_FUNCIONARIO NUMBER NOT NULL,
		NOME VARCHAR2(250) NOT NULL,
		CARGO VARCHAR2 (250) NOT NULL, 
		CONSTRAINT FUNCIOANRIOS_PK PRIMARY KEY (ID_FUNCIONARIO)
);

CREATE TABLE LABDATABASE.LOCACOES (
		NUMERO_RESERVA NUMBER NOT NULL, 
		DATA_INICIO DATE NOT NULL,
		DATA_FIM DATE NOT NULL,
		CPF VARCHAR2(11) NOT NULL,
		ID_VEICULO NUMBER NOT NULL,
		ID_FUNCIONARIO NUMBER NOT NULL,
		CONSTRAINT LOCACOES_PK PRIMARY KEY (NUMERO_RESERVA)
);

/*Cria as sequences*/
CREATE SEQUENCE LABDATABASE.CARROS_ID_CARRO_SEQ;
CREATE SEQUENCE LABDATABASE.FUNCIONARIOS_ID_FUNCIONARIO_SEQ;
CREATE SEQUENCE LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ;

/*Cria os relacionamentos*/
ALTER TABLE LABDATABASE.LOCACOES ADD CONSTRAINT CLIENTES_LOCACOES_FK
FOREIGN KEY (CPF)
REFERENCES LABDATABASE.CLIENTES (CPF)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.LOCACOES ADD CONSTRAINT CARROS_LOCACOES_FK
FOREIGN KEY (ID_CARRO)
REFERENCES LABDATABASE.CARROS (ID_CARRO)
NOT DEFERRABLE;

ALTER TABLE LABDATASE.LOCACOES ADD CONSTRAINT FUNCIONARIOS_LOCACOES_FK
FOREIGN KEY (ID_FUNCIONARIO)
REFERENCES LABDATABASE.FUNCIONARIOS (ID_FUNCIONARIO)
NOT DEFERRABLE;

/*Garante acesso total as tabelas*/
GRANT ALL ON LABDATABASE.CLIENTES TO LABDATABASE;
GRANT ALL ON LABDATABASE.CARROS TO LABDATABASE;
GRANT ALL ON LABDATABASE.FUNCIONARIOS TO LABDATABASE;
GRANT ALL ON LABDATABASE.LOCACOES TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited ON USERS;
