
INSERT INTO LABDATABASE.CLIENTES VALUES('296', 'Emanoel Vitor', '123');
INSERT INTO LABDATABASE.CLIENTES VALUES('201', 'Rogeres', '343');
INSERT INTO LABDATABASE.CLIENTES VALUES('790', 'Felipe Barzilai', '444');
INSERT INTO LABDATABASE.CLIENTES VALUES('995', 'Joao Emanoel', '985');
INSERT INTO LABDATABASE.CLIENTES VALUES('466', 'Livia Neves', '888');


INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'HB20S', 'PPH1234', 'Basico', 100);
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'Ferrari PuroSangue', 'HCA4321', 'Luxo', 500);
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'Volvo XC60', 'CEW7766', 'Comfort', 300);
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'GOL', 'LLM1234', 'Basico', 100);
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'Jetta', 'AAA7766', 'Comfort', 300);
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'Porsche', 'EEE7236', 'Luxo', 500);


INSERT INTO LABDATABASE.FUNCIONARIOS VALUES(FUNCIONARIOS_ID_FUNCIONARIO_SEQ.NEXTVAL, 'Howard', 'Gerente');
INSERT INTO LABDATABASE.FUNCIONARIOS VALUES(FUNCIONARIOS_ID_FUNCIONARIO_SEQ.NEXTVAL, 'Fulano', 'Atendente');
INSERT INTO LABDATABASE.FUNCIONARIOS VALUES(FUNCIONARIOS_ID_FUNCIONARIO_SEQ.NEXTVAL, 'Ciclano', 'Atendente');

COMMIT;
