

BEGIN
    INSERT INTO LABDATABASE.LOCACOES 
    (NUMERO_RESERVA, DATA_INICIO, DATA_FIM, ID_CLIENTE, ID_CARRO, ID_FUNCIONARIO)
    VALUES (
        LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ.NEXTVAL,
        TO_DATE('2025-10-21','YYYY-MM-DD'),
        TO_DATE('2025-10-23','YYYY-MM-DD'),
        (SELECT ID_CLIENTE FROM LABDATABASE.CLIENTES WHERE CPF ='789'),
        (SELECT ID_CARRO FROM LABDATABASE.CARROS WHERE PLACA = 'HCA4321'),
        2
    );

    INSERT INTO LABDATABASE.LOCACOES 
    (NUMERO_RESERVA, DATA_INICIO, DATA_FIM, ID_CLIENTE, ID_CARRO, ID_FUNCIONARIO)
    VALUES (
        LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ.NEXTVAL,
        TO_DATE('2025-10-22','YYYY-MM-DD'),
        TO_DATE('2025-10-25','YYYY-MM-DD'),
         (SELECT ID_CLIENTE FROM LABDATABASE.CLIENTES WHERE CPF ='123'),
        (SELECT ID_CARRO FROM LABDATABASE.CARROS WHERE PLACA = 'CEW7766'),
        3
    );

    INSERT INTO LABDATABASE.LOCACOES 
    (NUMERO_RESERVA, DATA_INICIO, DATA_FIM, ID_CLIENTE, ID_CARRO, ID_FUNCIONARIO)
    VALUES (
        LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ.NEXTVAL,
        TO_DATE('2025-10-24','YYYY-MM-DD'),
        TO_DATE('2025-10-26','YYYY-MM-DD'),
        (SELECT ID_CLIENTE FROM LABDATABASE.CLIENTES WHERE CPF ='321'),
        (SELECT ID_CARRO FROM LABDATABASE.CARROS WHERE PLACA = 'LLM1234'),
        1
    );

    INSERT INTO LABDATABASE.LOCACOES 
    (NUMERO_RESERVA, DATA_INICIO, DATA_FIM, ID_CLIENTE, ID_CARRO, ID_FUNCIONARIO)
    VALUES (
        LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ.NEXTVAL,
        TO_DATE('2025-10-24','YYYY-MM-DD'),
        TO_DATE('2025-10-28','YYYY-MM-DD'),
        (SELECT ID_CLIENTE FROM LABDATABASE.CLIENTES WHERE CPF ='456'),
        (SELECT ID_CARRO FROM LABDATABASE.CARROS WHERE PLACA = 'AAA7766'),
        2
    );

    COMMIT;
END;