/*INSERE DADOS NA TABELA DE CLIENTES*/
INSERT INTO LABDATABASE.CLIENTES VALUES('29603994049', 'Emanoel Vitor', '123456789');
INSERT INTO LABDATABASE.CLIENTES VALUES('20121192040', 'Rogeres', '343532344');
INSERT INTO LABDATABASE.CLIENTES VALUES('79048584019', 'Felipe Barzilai', '444444124');
INSERT INTO LABDATABASE.CLIENTES VALUES('99517999062', 'Joao Emanoel', '985674326');
INSERT INTO LABDATABASE.CLIENTES VALUES('46626884000', 'Livia Neves', '333123543');

/*INSERE DADOS NA TABELA DE CARROS*/
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'HB20S', 'PPH1234', 'Basico');
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'Ferrari PuroSangue', 'HCA4321', 'Luxo');
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'Volvo XC60', 'CEW7766', 'Comfort');
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'HB20', 'LLM1234', 'Basico');
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'Jetta', 'AAA7766', 'Comfort');
INSERT INTO LABDATABASE.CARROS VALUES(CARROS_ID_CARRO_SEQ.NEXTVAL, 'Focus', 'EEE7236', 'Basico');

/*INSERE DADOS NA TABELA DE FUNCIONARIOS*/
INSERT INTO LABDATABASE.FUNCIONARIOS VALUES(FUNCIONARIOS_ID_FUNCIONARIO_SEQ.NEXTVAL, 'Howard', 'Gerente');
INSERT INTO LABDATABASE.FUNCIONARIOS VALUES(FUNCIONARIOS_ID_FUNCIONARIO_SEQ.NEXTVAL, 'Fulano', 'Atendente');
INSERT INTO LABDATABASE.FUNCIONARIOS VALUES(FUNCIONARIOS_ID_FUNCIONARIO_SEQ.NEXTVAL, 'Ciclano', 'Atendente');

COMMIT;
