/*INSERE DADOS NA TABELA DE LOCACOES*/

INSERT INTO LABDATABASE.LOCACOES 
(NUMERO_RESERVA, DATA_INICIO, DATA_FIM, CPF, ID_VEICULO, ID_FUNCIONARIO)
VALUES (
    LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ.NEXTVAL,
    TO_DATE('2025-10-20','YYYY-MM-DD'),
    TO_DATE('2025-10-22','YYYY-MM-DD'),
    '29603994049',
    (SELECT ID_CARRO FROM LABDATABASE.CARROS WHERE PLACA='PPH1234'),
    1
);

INSERT INTO LABDATABASE.LOCACOES 
(NUMERO_RESERVA, DATA_INICIO, DATA_FIM, CPF, ID_VEICULO, ID_FUNCIONARIO)
VALUES (
    LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ.NEXTVAL,
    TO_DATE('2025-10-21','YYYY-MM-DD'),
    TO_DATE('2025-10-23','YYYY-MM-DD'),
    '20121192040',
    (SELECT ID_CARRO FROM LABDATABASE.CARROS WHERE PLACA='HCA4321'),
    2
);

INSERT INTO LABDATABASE.LOCACOES 
(NUMERO_RESERVA, DATA_INICIO, DATA_FIM, CPF, ID_VEICULO, ID_FUNCIONARIO)
VALUES (
    LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ.NEXTVAL,
    TO_DATE('2025-10-22','YYYY-MM-DD'),
    TO_DATE('2025-10-25','YYYY-MM-DD'),
    '79048584019',
    (SELECT ID_CARRO FROM LABDATABASE.CARROS WHERE PLACA='CEW7766'),
    3
);

INSERT INTO LABDATABASE.LOCACOES 
(NUMERO_RESERVA, DATA_INICIO, DATA_FIM, CPF, ID_VEICULO, ID_FUNCIONARIO)
VALUES (
    LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ.NEXTVAL,
    TO_DATE('2025-10-24','YYYY-MM-DD'),
    TO_DATE('2025-10-26','YYYY-MM-DD'),
    '99517999062',
    (SELECT ID_CARRO FROM LABDATABASE.CARROS WHERE PLACA='LLM1234'),
    1
);

INSERT INTO LABDATABASE.LOCACOES 
(NUMERO_RESERVA, DATA_INICIO, DATA_FIM, CPF, ID_VEICULO, ID_FUNCIONARIO)
VALUES (
    LABDATABASE.LOCACOES_NUMERO_RESERVA_SEQ.NEXTVAL,
    TO_DATE('2025-10-24','YYYY-MM-DD'),
    TO_DATE('2025-10-28','YYYY-MM-DD'),
    '46626884000',
    (SELECT ID_CARRO FROM LABDATABASE.CARROS WHERE PLACA='AAA7766'),
    2
);

COMMIT;

