SELECT
loc.NUMERO_RESERVA,
loc.DATA_INICIO,
loc.DATA_FIM,
loc.CPF,
loc.ID_VEICULO,
car.MODELO,
loc.ID_FUNCIONARIO,
cli.NOME_CLIENTE
FROM LOCACOES loc
INNER JOIN CLIENTES cli
ON loc.CPF = cli.CPF
INNER JOIN CARROS car
ON loc.ID_VEICULO = car.ID_VEICULO
ORDER BY loc.NUMERO_RESERVA